import { Geist, Geist_Mono, Merriweather, Open_Sans } from "next/font/google"; // Added Open_Sans
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["400", "700"], // Specify font weights (regular and bold)
});

// Added Open Sans font
const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"], // Specify font weights
});

export const metadata = {
  title: "Edgar's Personal Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} ${openSans.variable} antialiased`} // Added Open Sans variable
      >
        {children}
      </body>
    </html>
  );
}
